modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="lilwings"
version="${file.jarVersion}"
displayName="Lil' Wings"
#logoFile="logo.png"
authors="Kekie6, abused_master"
description='''
Lil' Adorable butterflies dancing on rainbows!
'''

[[dependencies.lilwings]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lilwings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
